version: '3'

services:
  fastapi:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    ports:
      - "3201:80"
    volumes:
      - ./fastapi:/app
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app

  golang:
    image: golang:latest
    command: go run /app/main.go
    ports:
      - "3202:8001"
    volumes:
      - ./golang:/app
    privileged: true

  flask:
    image: python:3.8
    command: >
      sh -c "pip install flask && python /app/app.py"
    ports:
      - "3203:8002"
    volumes:
      - ./flask:/app
    privileged: true

  django:
    image: python:3.8
    command: >
      sh -c "pip install django && python /app/manage.py runserver 0.0.0.0:8003"
    ports:
      - "3204:8003"
    volumes:
      - ./django:/app
    privileged: true
